#include <iostream>
#include <Windows.h>
#include <conio.h>
using namespace std;
void main()
{
	setlocale(0, "ru");
	int color_text = 0, color_fon = 0;
	HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
	char a = 0;
	SetConsoleCursorPosition(h, { 28, 1 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "**********";
	SetConsoleCursorPosition(h, { 27, 2 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "*****************";
	SetConsoleCursorPosition(h, { 32, 3 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "****";
	SetConsoleCursorPosition(h, { 30, 4 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "******";
	SetConsoleCursorPosition(h, { 32, 5 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "******";
	SetConsoleCursorPosition(h, { 38, 3 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "*";
	SetConsoleCursorPosition(h, { 38, 4 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "******";
	SetConsoleCursorPosition(h, { 40, 5 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "******";
	SetConsoleCursorPosition(h, { 27, 4 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "*";
	SetConsoleCursorPosition(h, { 27, 5 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "*";
	SetConsoleCursorPosition(h, { 28, 6 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "********";
	SetConsoleCursorPosition(h, { 28, 7 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "***************";
	SetConsoleCursorPosition(h, { 27, 3 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*****";
	SetConsoleCursorPosition(h, { 28, 4 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 28, 5 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 29, 5 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 29, 4 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 29, 5 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "***";
	SetConsoleCursorPosition(h, { 26, 4 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 26, 5 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 26, 6 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "**";
	SetConsoleCursorPosition(h, { 36, 3 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "**";
	SetConsoleCursorPosition(h, { 36, 4 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "**";
	SetConsoleCursorPosition(h, { 38, 5 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "**";
	SetConsoleCursorPosition(h, { 36, 6 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "********";
	SetConsoleCursorPosition(h, { 26, 9 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "****";
	SetConsoleCursorPosition(h, { 27, 8 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "***";
	SetConsoleCursorPosition(h, { 25, 10 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*****";
	SetConsoleCursorPosition(h, { 30, 8 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "**";
	SetConsoleCursorPosition(h, { 30, 9 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "**";
	SetConsoleCursorPosition(h, { 30, 10 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "**";
	SetConsoleCursorPosition(h, { 32, 10 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "******";
	SetConsoleCursorPosition(h, { 36, 9 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "**";
	SetConsoleCursorPosition(h, { 32, 9 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "****";
	SetConsoleCursorPosition(h, { 32, 8 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "**********";
	SetConsoleCursorPosition(h, { 38, 9 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "******";
	SetConsoleCursorPosition(h, { 38, 10 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "********";
	SetConsoleCursorPosition(h, { 40, 11 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "**";
	SetConsoleCursorPosition(h, { 38, 11 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "**";
	SetConsoleCursorPosition(h, { 36, 11 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "**";
	SetConsoleCursorPosition(h, { 30, 11 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "**";
	SetConsoleCursorPosition(h, { 32, 11 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "****";
	SetConsoleCursorPosition(h, { 28, 11 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "**";
	SetConsoleCursorPosition(h, { 25, 11 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "***";
	SetConsoleCursorPosition(h, { 25, 12 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "****";
	SetConsoleCursorPosition(h, { 25, 13 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "**";
	SetConsoleCursorPosition(h, { 28, 11 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "**";
	SetConsoleCursorPosition(h, { 27, 11 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*";
	SetConsoleCursorPosition(h, { 28, 12 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "************";
	SetConsoleCursorPosition(h, { 27, 13 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "***************";
	SetConsoleCursorPosition(h, { 42, 11 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "****";
	SetConsoleCursorPosition(h, { 40, 12 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "******";
	SetConsoleCursorPosition(h, { 42, 13 });
	SetConsoleTextAttribute(h, 14 * 16 + 14);
	cout << "****";
	SetConsoleCursorPosition(h, { 27, 14 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "*****";
	SetConsoleCursorPosition(h, { 36, 14 });
	SetConsoleTextAttribute(h, 12 * 16 + 12);
	cout << "******";
	SetConsoleCursorPosition(h, { 26, 15 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*****";
	SetConsoleCursorPosition(h, { 37, 15 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "******";
	SetConsoleCursorPosition(h, { 25, 16 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "******";
	SetConsoleCursorPosition(h, { 37, 16 });
	SetConsoleTextAttribute(h, 10 * 16 + 10);
	cout << "*******";
	system("pause >> NUL");
}
